#!/bin/env sh

logfile=~/research-projects/iperf3-logs/"$(date +'%Y-%m-%d-%H:%M')-iperf3-generator.log"
container_id=$(docker ps -a | grep iperf-generator | awk '{print $1}')
docker cp ${container_id}:root/iperf3_generator.log ${logfile}
