#!/usr/bin/env bash

set -euo pipefail

logfile=~/research-projects/iperf3-logs/"$(date +'%Y-%m-%d-%H:%M')-iperf3-generator.log"
container_id=$(docker ps -a --filter "name=iperf-generator" --format "{{.ID}}")

if [[ -z "${container_id}" ]]; then
    echo "No container found with the name containing 'multi-traffic-generator'"
    exit 1
fi

docker cp "${container_id}:root/iperf3_generator.log" "${logfile}"
