#!/usr/bin/env bash

set -euo pipefail

# Simpl script to copy most recently downloaded file
# to the cwd

down_file="$(ls -Art ~/Downloads | tail -n1)"
# -A for all but ./ and ../
# -r for reversed output
# -t for sorted by time, newest first

# https://stackoverflow.com/questions/4561895/how-to-recursively-find-the-latest-modified-file-in-a-directory
# down_file="$(find . -type f -printf '%T@ %p\n' \
#     | sort -n | tail -1 | cut -f2- -d' ')"

if [[ -z "$down_file" ]]; then
    echo "No new downloaded files"
    exit 42
fi

file_path="$HOME/Downloads/$down_file"

if [[ $# -eq 0 ]]; then
    dest="."
elif [[ $# -eq 1 ]]; then
    dest="$1"
else
    echo "Expected at most one argument for dest file path"
    exit 42
fi

mv -i "${file_path}" "$dest"
echo "Moved '$file_path' to '$dest'"
